#!/bin/bash
SRC_DIR="$(pwd)"

#mkdir "${SRC_DIR}/log/expectedArmCompilerOutput"
#mkdir "${SRC_DIR}/log/actualExecuteOutput"

VALID_EXAMPLES=$(find "${SRC_DIR}/test/wacc_examples/valid")
EXPECTED_OUTPUT_DIR= "${SRC_DIR}/log/expectedOutput"
EXECUTE_OUTPUT_DIR= "${SRC_DIR}/log/actualExecuteOutput"

TOTAL_COUNT=$(find ${VALID_EXAMPLES[@]} -name "*.wacc" | wc -l)
COUNTER=0
PASSED=0
FAILED=0


echo "=============================Valid Case Test============================================"
echo "Correct Program must have expected output matches the execute output"
echo "========================================================================================"

for folder in ${VALID_EXAMPLES[@]}; do
    EXPECTED_OUTPUT_FOLDER="${SRC_DIR}/log/expectedOutput/$(basename folder)"
    EXECUTE_OUTPUT_FOLDER="${SRC_DIR}/log/actualExecuteOutput/$(basename folder)"

  for file in $(find "$folder" -name "*.wacc"); do
    FILEBASENAME=$(basename -s .wacc "${file}")
    EXPECTED_FILE_NAME="${EXPECTED_OUTPUT_FOLDER}/${FILE_NAME}"
    EXECUTE_FILE_NAME="${EXECUTE_OUTPUT_FOLDER}/${FILE_NAME}"
    ./compile $file > "${EXPECTED_FILE_NAME}.log.txt"
    mv "${FILE_NAME}.s" "${EXPECTED_FILE_NAME}.s"

    arm-linux-gnueabi-gcc -o $EXECUTE_FILE_NAME -mcpu=arm1176jzf-s -mtune=arm1176jzf-s "${EXPECTED_FILE_NAME}.s" > "${EXECUTE_FILE_NAME}.log.txt"
    qemu-arm -L /usr/arm-linux-gnueabi/ $EXECUTE_FILE_NAME > "${EXECUTE_FILE_NAME}.output.txt"

    (( COUNTER += 1 ))
    if [[$EXECUTE_FILE_NAME == $EXPECTED_FILE_NAME]]; then
      (( PASSED += 1 ))
    fi

  done
done


echo "================================TEST RESULT============================================="
echo "Total Test: " $TOTAL_COUNT
echo "Passed Test:" $PASSED
echo "Failed Test:" $(TOTAL_COUNT - PASSED)
echo "========================================================================================"

if [[ $((FAILED)) -gt 0 ]]; then
  exit -1
fi
