#!/bin/bash
INVALID_SEMANTIC_EXAMPLES=(
                "test/wacc_examples/invalid/semanticErr/exit"
                "test/wacc_examples/invalid/semanticErr/expressions"
                "test/wacc_examples/invalid/semanticErr/function"
                "test/wacc_examples/invalid/semanticErr/if"
                "test/wacc_examples/invalid/semanticErr/IO"
                "test/wacc_examples/invalid/semanticErr/multiple"
                "test/wacc_examples/invalid/semanticErr/pairs"
                "test/wacc_examples/invalid/semanticErr/print"
                "test/wacc_examples/invalid/semanticErr/read"
                "test/wacc_examples/invalid/semanticErr/scope"
                "test/wacc_examples/invalid/semanticErr/variables"
                "test/wacc_examples/invalid/semanticErr/while")


TOTAL_COUNT=$(find ${INVALID_SEMANTIC_EXAMPLES[@]} -name "*.wacc" | wc -l)
COUNTER=1
PASSED=0
FAILED=0

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

echo "=============================Valid Case Test============================================"
echo "Invalid Semantic program must have exit code of 200"
echo "========================================================================================"

for folder in ${INVALID_SEMANTIC_EXAMPLES[@]}; do
  # shellcheck disable=SC2044
  for file in $(find "$folder" -name "*.wacc"); do
    ./compile "$file" >tmp 2>tmp
    # ./grun antlr.WACC program -tokens "$file" >tmp 2>tmp
    ret=$?
    if [ $ret -ne 200 ]; then
      echo "${red}TEST" $COUNTER "FAILED: Exit Status of" $ret " for " $file "${reset}"
      FAILED=$((FAILED+1))
    else
      echo "${green}TEST" $COUNTER "PASSED: " $file "${reset}"
      PASSED=$((PASSED+1))
    fi

    COUNTER=$((COUNTER+1))
  done

done

echo "================================TEST RESULT============================================="
echo "Total Test: " $TOTAL_COUNT
echo "Passed Test:" $PASSED
echo "Failed Test:" $FAILED
echo "========================================================================================"