#!/bin/bash
INVALID_TEST_FOLDER=$3
VALID_TEST_FOLDER=$2
EXPECTED_ERROR_CODE=$1


COUNTER=0
PASSED=0
FAILED=0

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput init`

echo "Start Testing"

for file in $(find "$VALID_TEST_FOLDER" -name "*.wacc" 2> tmp); do
    ./compile "$file" >tmp 2>tmp
    # ./grun antlr.WACC program -tokens "$file" > tmp
    ret=$?
    if [ $ret -ne 0 ]; then
      echo "${red}TEST" $COUNTER "FAILED: Expect 0 but got" $ret "for" $file "${reset}"
      FAILED=$((FAILED+1))
    else
      echo "${green}TEST" $COUNTER "PASSED:" $file "${reset}"
      PASSED=$((PASSED+1))
    fi

    COUNTER=$((COUNTER+1))
done

for file in $(find "$INVALID_TEST_FOLDER" -name "*.wacc"); do
    ./compile "$file" >tmp 2>tmp
    # ./grun antlr.WACC program -tokens "$file" > tmp
    ret=$?
    if [ $ret -ne $((EXPECTED_ERROR_CODE)) ]; then
      echo "${red}TEST" $COUNTER "FAILED: Expect" $((EXPECTED_ERROR_CODE)) "but got"  $ret "for" $file "${reset}"
      FAILED=$((FAILED+1))
    else
      echo "${green}TEST" $COUNTER "PASSED:" $file "${reset}"
      PASSED=$((PASSED+1))
    fi

    COUNTER=$((COUNTER+1))
done


echo "================================TEST RESULT============================================="
echo "Total Test: " $COUNTER
echo "Passed Test:" $PASSED
echo "Failed Test:" $FAILED
echo "========================================================================================"

if [[ $((FAILED)) -gt 0 ]]; then
  exit -1
fi
