stages:
  - build
  - test

build-job:
  stage: build
  script:
    - make

valid-test-job:
  stage: test
  script:
    - make
    - /bin/bash test/testValid

invalid-syntax-test-job:
  stage: test
  script:
    - make
    - /bin/bash test/testInvalidSyntax

invalid-semantics-test-job:
  stage: test
  script:
    - make
    - /bin/bash test/testInvalidSemantic

  

