stages:
  - build
  - test-syntax
  - test-semantic
  - test-general
  - test-backend

variables:
  VALID_TEST_DIR: "test/wacc_examples/valid"
  INVALID_SYNTAX_TEST_DIR: "test/wacc_examples/invalid/syntaxErr"
  INVALID_SEMANTIC_TEST_DIR: "test/wacc_examples/invalid/semanticErr"

build-job:
  stage: build
  script:
    - make clean
    - make
  artifacts:
    paths:
      - bin/
      - src/antlr

array-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/array "$INVALID_SYNTAX_TEST_DIR"/array

basic-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/basic "$INVALID_SYNTAX_TEST_DIR"/basic

expressions-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/expressions "$INVALID_SYNTAX_TEST_DIR"/expressions

function-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/function "$INVALID_SYNTAX_TEST_DIR"/function

if-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/if "$INVALID_SYNTAX_TEST_DIR"/if

pairs-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/pairs "$INVALID_SYNTAX_TEST_DIR"/pairs

print-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "" "$INVALID_SYNTAX_TEST_DIR"/print

sequence-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/sequence "$INVALID_SYNTAX_TEST_DIR"/sequence

variables-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/variables "$INVALID_SYNTAX_TEST_DIR"/variables

while-syntax-test:
  stage: test-syntax
  script:
    - /bin/bash test/test 100 "$VALID_TEST_DIR"/while "$INVALID_SYNTAX_TEST_DIR"/while

exit-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/exit

expressions-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/expressions

function-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/function

if-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/if

io-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "$VALID_TEST_DIR"/io "$INVALID_SEMANTIC_TEST_DIR"/io

multiple-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/multiple

pairs-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/pairs

print-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/print

read-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/read

scope-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "$VALID_TEST_DIR"/scope "$INVALID_SEMANTIC_TEST_DIR"/scope

variables-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/variables

while-semantic-test:
  stage: test-semantic
  script:
    - /bin/bash test/test 200 "" "$INVALID_SEMANTIC_TEST_DIR"/while

advanced-general-test:
  stage: test-general
  script:
    - /bin/bash test/test 0 "" "$VALID_TEST_DIR"/advanced

runtimeErr-general-test:
  stage: test-general
  script:
    - /bin/bash test/test 0 "" "$VALID_TEST_DIR"/runtimeErr

backend-test:
  stage: test-backend
  script:
    - /bin/bash backEndTest.sh
  

