stages:
  - build
  - test

build-job:
  stage: build
  script:
    - make -f Makefile
  artifacts:
    paths:
      - target/  

valid-test-job:
  stage: test
  script:
    - ./testValid

invalid_syntax-test-job:
  stage: test
  script:
    - ./testInvalidSyntax

invalid_semantic-test-job:
  stage: test
  script:
    - ./testInvalidSemantic




  

