stages:
  - build
  - test

build-job:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - target/  

parser-test-job:
  stage: test
  script:
    - ./src/test/compile/ParserTest.sh




  

