stages:
  - build
  - test

build-job:
  stage: build
  script:
    - make

valid-test-job:
  stage: test
  script:
    - pwd
    - ./testValid

invalid_syntax-test-job:
  stage: test
  script:
    - ./testInvalidSyntax

invalid_semantic-test-job:
  stage: test
  script:
    - ./testInvalidSemantic




  

