#!/bin/bash
# Bash front end for the compiler
# You are free to change the language used for this script,
# but do *not* change its name.

if [ -z $1 ]
then
    echo "No file/path has been supplied!";
fi

# compile the given wacc file here
kotlin -cp ./bin:./lib/antlr-4.9.3-complete.jar TestKt $1